import {Dimensions, StyleSheet} from 'react-native';
import { vh, vw } from '../../utils/dimension';
import { colors } from '../../theme';
const {width: screenWidth} = Dimensions.get('window');
export default StyleSheet.create({
    timeIMg: {
        width: vh(14.5),
        height: vh(14.5),
      },
      locImg: {
        width: vh(12),
        height: vh(14.5),
      },
      dealerImg: {
        width: vh(118),
        height: vh(118),
        borderRadius: vh(8),
      },
      mapFlex: {
        flex: 1,
      },
      cardRow: {
        flexDirection: 'row',
      },
      flatStyle: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
      },
      directionImg: {
        width: vh(14),
        height: vh(14),
        tintColor: '#7C8585',
        marginRight: vh(8),
      },
      callImg: {
        width: vh(12.5),
        height: vh(12.5),
        tintColor: '#7C8585',
        marginRight: vh(8),
      },
      emailImg: {
        width: vh(13),
        height: vh(10),
        tintColor: '#7C8585',
        marginRight: vh(8),
      },
      container: {flex: 1, backgroundColor: '#fff', paddingTop: vh(22)},
      header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: vh(12),
        marginTop: vh(12),
      },
      headerText: {fontSize: vh(20), fontWeight: 'bold', marginLeft: vw(10)},
      backButton: {width: vh(40), height: vh(40), resizeMode: 'contain'},
      dropdownContainer: {
        flexDirection: 'row',
        paddingHorizontal: vh(10),
        paddingVertical: vh(10),
        justifyContent: 'space-between',
      },
      dropdown: {
        flex: 1,
        marginHorizontal: vw(5),
      },
      dropDownPicker: {
        borderColor: '#D4DAEA',
        borderWidth: 1,
      },
      dropDownContainer: {
        borderColor: '#D4DAEA',
        borderWidth: 1,
        width: '100%',
      },
      map: { ...StyleSheet.absoluteFillObject },
      dealerCard: {
        backgroundColor: '#fff',
        paddingVertical: vh(16),
        // marginVertical: vh(5),
        paddingHorizontal: vh(12),
        borderRadius: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
      },
      dealerName: {
        fontSize: vh(18),
        fontWeight: '500',
        color: '#222',
        marginBottom: vh(4),
      },
      dealerService: {
        fontSize: vh(12),
        fontWeight: '400',
        color: '#050507',
        marginBottom: vh(9.5),
      },
      dealerAddress: {
        fontSize: vh(12),
        color: '#7C8585',
        fontWeight: '400',
        lineHeight: vh(14.4),
        marginBottom: vh(8),
        marginLeft: vh(6),
      },
      dealerTime: {
        fontSize: vh(12),
        color: '#7C8585',
        fontWeight: '400',
        lineHeight: vh(14.4),
        marginBottom: vh(8),
        paddingEnd: vh(17),
        marginLeft: vh(6),
      },
      logo: {
        width: vh(65),
        height: vh(8),
        marginBottom: vh(8),
      },
      buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: vh(16),
        width: screenWidth - vh(24),
      },
      button: {
        backgroundColor: '#fff',
        padding: vh(8),
        flexDirection: 'row',
        borderRadius: 5,
        width: screenWidth / 4 - 3,
        height: vh(36),
        borderWidth: 1,
        borderColor: '#D4DAEA',
        justifyContent: 'center',
        alignItems: 'center',
      },
    
      directionButton: {
        backgroundColor: '#fff',
        padding: vh(8),
        flexDirection: 'row',
        borderRadius: 5,
        width: screenWidth / 4 + vh(57),
        height: vh(36),
        borderWidth: 1,
        borderColor: '#D4DAEA',
        justifyContent: 'center',
        alignItems: 'center',
      },
      selectdirectButton: {
        borderWidth: 1,
        borderColor: colors.primary,
        padding: vh(8),
        flexDirection: 'row',
        borderRadius: 5,
        width: screenWidth / 4 + vh(59),
        height: vh(36),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 0, 0, 0.1)',
      },
      selectButton: {
        borderWidth: 1,
        borderColor: colors.primary,
        padding: vh(8),
        flexDirection: 'row',
        borderRadius: 5,
        width: screenWidth / 4 - vh(3),
        height: vh(36),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 0, 0, 0.1)',
      },
      buttonText: {
        color: '#7C8585',
        fontSize: vh(14),
        fontWeight: '500',
      },
      dealerContent: {
        marginStart: vh(12),
        width: screenWidth / 2 + vh(50),
      },
})