
const Images = {
  
  splash: require('./images/splash.png'),
  back:require('./images/back.png'),
  backarrow:require('./images/backarrow.png'),
  converston: require('./images/conversion.png'),
  gps: require('./images/gps.png'),
  gpsindicator: require('./images/gpsindicator.png'),
  calendar: require('./images/calendar.png'),
  user: require('./images/user.png'),
  search : require('./images/search.png'),
  hotel: require('./images/hotel.png'),
  honda:require('./images/honda.png'),
  tutorial1: require('./images/tutorial1.png'),
  tutorial2: require('./images/tutorial2.png'),
  tutorial3: require('./images/tutorial3.png'),
  customer:  require('./images/customer.png'),
  retailer:  require('./images/retailer.png'),
  dealer:  require('./images/dealer.png'),
  employe:  require('./images/employe.png'),
  checkmark : require('./images/checkmark.png'),
  promotionIcon:require('./images/promotionIcon.png'),
  trainingIcon:require('./images/trainingIcon.png'),
  moreIcon:require('./images/moreIcon.png'),
  homeIcon:require('./images/homeIcon.png'),
  categoryIcon:require('./images/categoryIcon.png'),
  notification:require('./images/notification.png'),
  hi:require('./images/hi+.png'),
  right:require('./images/right.png'),
  hivaluelogo:require('./images/hivaluelogo.png'),
  machinery:require('./images/machinery.png'),
  other:require('./images/other.png'),
  tiller:require('./images/tiller.png'),
  WB:require('./images/WB.png'),
  agriculture:require('./images/agriculture.png'),
  battery:require('./images/battery.png'),
  bf200:require('./images/bf200.png'),
  f300:require('./images/f300.png'),
  dealerImg:require('./images/dealerImg.png'),
  timer:require('./images/timer.png'),
  email:require('./images/email.png'),
  call:require('./images/call.png'),
  direction:require('./images/direction.png'),
  location: require('./images/location.png'),
  time:require('./images/time.png'),
};

export {Images};
