
const Images = {
  back:require('./images/back.png'),
  backarrow:require('./images/backarrow.png'),
  converston: require('./images/conversion.png'),
  gps: require('./images/gps.png'),
  gpsindicator: require('./images/gpsindicator.png'),
  calendar: require('./images/calendar.png'),
  user: require('./images/user.png'),
  search : require('./images/search.png'),
  hotel: require('./images/hotel.png'),
  honda:require('./images/honda.png'),
  tutorial1: require('./images/tutorial1.png'),
  tutorial2: require('./images/tutorial2.png'),
  tutorial3: require('./images/tutorial3.png'),
  customer:  require('./images/customer.png'),
  retailer:  require('./images/retailer.png'),
  dealer:  require('./images/dealer.png'),
  employe:  require('./images/employe.png'),
  checkmark : require('./images/checkmark.png'),
  promotionIcon:require('./images/promotionIcon.png'),
  trainingIcon:require('./images/trainingIcon.png'),
  moreIcon:require('./images/moreIcon.png'),
  homeIcon:require('./icons/homeTabEnable.png'),
  categoryIcon:require('./images/categoryIcon.png'),
  notification:require('./images/notification.png'),
  hi:require('./images/hi+.png'),
  hiValuePlusImage:require('./images/hiValuePlus.png'),
  right:require('./images/right.png'),
  hivaluelogo:require('./images/hivaluelogo.png'),
  machinery:require('./images/machinery.png'),
  other:require('./images/other.png'),
  tiller:require('./images/tiller.png'),
  WB:require('./images/WB.png'),
  agriculture:require('./images/agriculture.png'),
  battery:require('./images/battery.png'),
  bf200:require('./images/bf200.png'),
  f300:require('./images/f300.png'),
  dealerImg:require('./images/dealerImg.png'),
  timer:require('./images/timer.png'),
  downIcon: require('./images/down.png'),
  infoIcon: require('./icons/info.png'),
  bellIcon: require('./icons/bellIcon.png'),
  hondaHqImage: require('./images/HondaHQ.png'),
  faceBookIcon: require('./icons/facebookicon.png'),
  instaGramIcon: require('./icons/instaIcon.png'),
  expand: require('./images/expand.png'),
  unexpand:require('./images/unexpand.png'),
  sort: require('./images/sort.png'),
  filter: require('./images/filter.png'),
  close: require('./images/close.png'),
  hondaHqBig: require('./images/hondaHQBig.png'),
  phoneicon: require('./images/phoneIcon.png'),
  rightArrow: require('./icons/rightArrow.png'),
  calanderIcon: require('./icons/CalanderIcon.png'),
  notificationOn: require('./icons/notificationOn.png'),
  notificationOff: require('./icons/notificationOff.png'),
  notificationHome: require('./icons/notificationHomeBell.png'),
  dummyFile: require('./images/pdfSign.png'),
  dummyYouTube: require('./images/youtubeDummy.png'),
  tickIcon: require('./icons/tickIcon.png'),
  crossIcon: require('./icons/crossIcon.png'),
  selectRadio: require('./icons/selectedRadio.png'),
  unselectRadio: require('./icons/unselectRadio.png'),
  upArrow:  require('./icons/upArrow.png'),
  downArrow:  require('./icons/downArrow.png'),
  seeMoreRigthArrow:  require('./icons/seeMore.png'),
  hondaGenrator: require('./images/hondaGenrator.png'),
  hondaMotor: require('./images/hondaMotor.png'),
  clockIcon:  require('./icons/clockIcon.png'),
  pencilIcon:  require('./icons/pencilIcon.png'),
  dateCalanderIcon:  require('./icons/dateCalanderIcon.png'),
  threeDotIcon: require('./icons/threeDot.png'),
  uploadImageIcon: require('./icons/uploadImage.png'),
  callIconDull: require('./icons/callIconDull.png'),
  emailBoxDull: require('./icons/emailBoxDull.png'),
  directionIcon: require('./icons/direction.png'),
  locationIcon: require('./icons/loacationIcon.png'),
  timerIcon: require('./icons/timerIcon.png')
};

export {Images};
